version: '3'
services:
  myapp:
    container_name: myapp
    restart: always
    build: .
    ports:
      - '7000:7000'
    environment:
     - REDIS_HOST=myapp-redis
    links:
      - redis
    depends_on:
     - redis
  redis:
    container_name: myapp-redis
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'